The Artist/Controllers/ArtController.cs
using Microsoft.AspNetCore.Mvc;
using The_Artist.Models;
using The_Artist.Models.repositories;
using The_Artist.ViewModels;

namespace The_Artist.Controllers
{
    public class ArtController : Controller
    {
        private readonly IArtRepository<Art> artRepository;
        private readonly ArtListViewModel artListViewModel;

        public ArtController(IArtRepository<Art> artRepository)
        {
            this.artRepository = artRepository;
            artListViewModel = new ArtListViewModel();
        }

        public IActionResult Index()
        {
            artListViewModel.Arts = artRepository.List();

            return View(artListViewModel);
        }
        public IActionResult Category(int id)
        {
            artListViewModel.Arts = artRepository.GetArtByCategoryId(id);

            return View(artListViewModel);
        }
    }
}

The Artist/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using The_Artist.Models;
using The_Artist.Models.repositories;

namespace The_Artist.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactRepository<Contact> contactRepository;

        public ContactController(IContactRepository<Contact> contactRepository)
        {
            this.contactRepository = contactRepository;
        }

        public IActionResult Index()
        {
            var contactInfo = contactRepository.List();

            return View(contactInfo);
        }
    }
}

The Artist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/content/StyleSheet.css">
    @*@RenderSection("Styles", false)*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">The Artist</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Art</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Art" asp-action="Index">All</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Art" asp-action="Category" asp-route-id="1">Chairs</a></li>
                                <li><a class="dropdown-item" asp-controller="Art" asp-action="Category" asp-route-id="2">Hammers</a></li>
                                <li><a class="dropdown-item" asp-controller="Art" asp-action="Category" asp-route-id="3">Knives</a></li>
                                <li><a class="dropdown-item" asp-controller="Art" asp-action="Category" asp-route-id="4">Lamps</a></li>
                                <li><a class="dropdown-item" asp-controller="Art" asp-action="Category" asp-route-id="5">Boats</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
     <main class="d-sm-flex flex-wrap flex-row justify-content-center align-items-center py-2">
         @RenderBody();
     </main>
     <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
</body>
</html>